### ISSUE TITLE
[initCloud]删除云磁盘数据库中数据并未删除

### ISSUE THREAD

**Issue by XinchaoZ** [hitsub2/evercloud_repo#76]
将以前存在的云磁盘删除 后台数据库中数据并没有删除
![1](https://cloud.githubusercontent.com/assets/25816397/23600508/dc4962a6-0281-11e7-94e9-5c5929fcd547.png)
![1](https://cloud.githubusercontent.com/assets/25816397/23600519/e925d086-0281-11e7-9121-dd3f781bd242.png)

**Comment by hitsub2** [comment]
数据库字段deleted=0，表示未删除。deleted !=1表示删除。
